### POST request to create new patient entity
POST http://localhost:4000/patients
Content-type: application/json

{
  "name": "Marie Curie Billing",
  "email": "marie_billing_account@outlook.com",
  "address": "1234 Dummy Avenue",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2025-05-16"
}

### POST request without email
POST http://localhost:4000/patients
Content-type: application/json

{
  "name": "John Doe",
  "address": "5678 Nothing Avenue",
  "dateOfBirth": "1999-09-09",
  "registeredDate": "2025-05-16"
}

### POST request with duplicate email
POST http://localhost:4000/patients
Content-type: application/json

{
  "name": "Bob Harris",
  "email": "james.harris@example.com",
  "address": "2222 Another Street",
  "dateOfBirth": "2025-01-02",
  "registeredDate": "2025-05-16"
}

