### Valid login request to retrieve a token through the api-gateway
POST http://localhost:4004/auth/login
Content-Type: application/json

{
  "email": "testuser@test.com",
  "password": "password123"
}
> {% client.global.set("token", response.body.token) %}

### Valid login request to retrieve a token by hitting auth-service directly (port now closed)
POST http://localhost:4005/login
Content-Type: application/json

{
    "email": "testuser@test.com",
    "password": "password123"
}
> {% client.global.set("token", response.body.token) %}

### Invalid login request (nonexistent user, port now closed)
POST http://localhost:4005/login
Content-Type: application/json

{
  "email": "invalidemail@test.com",
  "password": "fakepassword1"
}

### Invalid login request (wrong password, port now closed)
POST http://localhost:4005/login
Content-Type: application/json

{
  "email": "testuser@test.com",
  "password": "wrongpassword123"
}